# render.yaml (en la raíz de tu repo)
services:
  # ------------ BACKEND ------------
  - type: web
    name: sigs-backend
    env: node
    branch: master
    rootDir: backend-mongodb
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://testingfrontend-6xbm.onrender.com
